name: Scheduled Workflow
run-name: Scheduled Workflow
on:
    push:
    schedule:
        - cron: "5 * * * *"
          timezone: "America/New_York"
jobs:
    run_every_5_mins:
        runs-on: ubuntu-latest
        steps:
            - name: "Announce job"
              run: echo "This job runs 5 minutes passed the hour or on a push"
