name: Manual-Workflow
run-name: Manual-Workflow
on: workflow_dispatch
jobs:
    run-manual-wf:
        runs-on: ubuntu-latest
        steps:
            - name: random-name
              uses: octodemo-resources/name-generator-action@eaebafb63565c11a483907f1f589adf02fa7be85
            - name: echo
              run: echo "This is a manual workflow that uses the workflow_dispatch event"
