name: Manual-Workflow
run-name:
    Manual-Workflow
on: workflow_dispatch
jobs:
    run-manual-wf:
        runs-on: ubuntu-latest
        steps: 
            - name: rick-roll
              uses: TejasvOnly/random-rickroll@f3c4666e06fe75516d208fad01bfcbde7b37ce1e
              with:
                percentage: 50
                GITHUB_TOKEN: ${{ github.token }}